# Generated by Django 2.1.5 on 2020-09-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200921_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='photo',
            new_name='picture',
        ),
    ]
